const Interests = [
  "Sports",
  "Music",
  "Gaming (video games, esports, table top)",
  "Memes",
  "Escape rooms",
  "Digital art (drawing, graphic design)",
  "Anime and manga fandom",
  "Family time",
  "Fitness and wellness (yoga, meditation, workout)",
  "Fashion",
  "Reading (fiction, web novels)",
  "Reading (Non fiction, self-help, history)",
  "Traveling",
  "Politics and activism",
  "Streaming content (Netflix, YouTube, Twitch)",
  "Podcasts",
  "Movies/film",
  "TV",
  "Coffee",
  "Among us",
  "Programming/Technology",
  "minecraft",
  "Entrepreneurship and side hustles",
  "Astrology",
  "True crime",
  "Food culture (cooking, trying new cuisines)",
  "Outdoor activities (hiking, camping, urban exploring)",
];

export default Interests;
